// Generated by https://quicktype.io

import { PaginationModel } from "../shared/models/pagination.model";

export interface PurchaseModel {
  productId: number;
  quantity: number;
  purchaseDate: string;
  description: string;
  unitPrice: number;
  productName: string;
  id: number;
  purchaseOrderNumber: string;
  invoiceNumber: string;
  receivedDate: string
}

export interface PaginatedPurchase extends PaginationModel {
  purchases: PurchaseModel[];
}
