@base_address = http://localhost:5131/api/products

# get
GET {{base_address}}

### get with params
# params : page = 1,  limit = 4,  searchTerm = "string"|null, string? sortColumn = "string"|null, string? sortDirection = "string"|null
GET {{base_address}}?searchTerm=product21

### get by id
GET {{base_address}}/3

### post
POST {{base_address}}
Content-Type: application/json

{
    "productName":"product2",
    "categoryId":11,
    "supplierId":2,
    "price":80
}

### put
PUT {{base_address}}/3
Content-Type: application/json

{
    "id":3,
    "productName":"product21",
    "categoryId":16,
    "supplierId":1,
    "price":81
}

### put
DELETE  {{base_address}}/3

### Products with stock
GET {{base_address}}/all-products-with-stock
