@base_address = http://localhost:5131/api/purchases

// get all
GET {{base_address}}

### get one
GET {{base_address}}/3

### post
POST  {{base_address}}
Content-Type: application/json

{
  "productId": 6,
  "quantity": 90.1,
  "purchaseDate": "2025-08-16",
  "unitPrice": 80.99,
  "description": "Bulk purchase"
}

### PUT

PUT {{base_address}}/3
Content-Type: application/json

{
  "id":3,
  "purchaseDate": "2025-08-16",
  "productId": 6,
  "quantity": 10,
  "unitPrice": 81.22,
  "description": "Bulk purchase"
}
