@base_address = http://localhost:5131/api/sales

### Get
GET {{base_address}}

### Get by id
GET {{base_address}}/4

### post
POST {{base_address}}
Content-Type: application/json

{
  "productId": 7,
  "quantity": 10,
  "price": 29.99,
  "sellingDate": "2025-08-15",
  "description": "Sale transaction ...."
}

### put
PUT {{base_address}}/4
Content-Type: application/json

{
  "id":4,
  "productId": 7,
  "quantity": 5,
  "price": 29.90,
  "sellingDate": "2025-08-16",
  "description": "Sale transaction ...."
}

### DELETE
DELETE {{base_address}}/4