@base_address = http://localhost:5131/api/auth
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6ImFkbWluIiwianRpIjoiMmYyMGYxNzgtOTY3NS00M2Y0LTgxNjItZjdhZDkxNTI5OThmIiwicm9sZSI6IkFkbWluIiwibmJmIjoxNzU1NzUzNTE0LCJleHAiOjE3NTU3NTM1NzQsImlhdCI6MTc1NTc1MzUxNCwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo1MTMxIiwiYXVkIjpbImh0dHA6Ly9sb2NhbGhvc3Q6NTEzMSIsImh0dHA6Ly9sb2NhbGhvc3Q6NTEzMSJdfQ.Kr_hdEpvpbDlD3SGbxg3miQ7NhXEbhQ3IOQYmvADpkA

POST {{base_address}}/login
Content-Type: application/json

{
    "username":"admin",
    "password":"Admin@123"
}

###
POST {{base_address}}/refresh
Content-Type: application/json

{
  "accessToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6ImFkbWluIiwianRpIjoiMmYyMGYxNzgtOTY3NS00M2Y0LTgxNjItZjdhZDkxNTI5OThmIiwicm9sZSI6IkFkbWluIiwibmJmIjoxNzU1NzUzNTE0LCJleHAiOjE3NTU3NTM1NzQsImlhdCI6MTc1NTc1MzUxNCwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo1MTMxIiwiYXVkIjpbImh0dHA6Ly9sb2NhbGhvc3Q6NTEzMSIsImh0dHA6Ly9sb2NhbGhvc3Q6NTEzMSJdfQ.Kr_hdEpvpbDlD3SGbxg3miQ7NhXEbhQ3IOQYmvADpkA",
  "refreshToken": "Hf7NG2erD/g6EiuWzN3jVBxOXxuTyMW16Y9AAZX9zUo="
}

###
GET {{base_address}}/me
Authorization: Bearer {{accessToken}}