@base_address = http://localhost:5131/api/auth
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6ImFkbWluIiwianRpIjoiMjQ0YWU5MzgtZWQ4Ni00YTk5LWIwZTEtMThmMzk3ODcyODE1Iiwicm9sZSI6IkFkbWluIiwibmJmIjoxNzU1Nzg2Njc1LCJleHAiOjE3NTU3ODY3MzUsImlhdCI6MTc1NTc4NjY3NSwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo1MTMxIiwiYXVkIjoiaHR0cDovL2xvY2FsaG9zdDo1MTMxIn0.H3liLMevFb3bBmf0MvFdfaKtVcG81SwTtT61tXAAo1Q

POST {{base_address}}/login
Content-Type: application/json

{
    "username":"admin",
    "password":"Admin@123"
}

###
POST {{base_address}}/refresh
Content-Type: application/json

{
  "accessToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6ImFkbWluIiwianRpIjoiZTk1YjUyNGItZGI2OC00NWQ1LWJlNTAtNDNlNGFlYjkyYjY1Iiwicm9sZSI6IkFkbWluIiwibmJmIjoxNzU1NzU2NTg1LCJleHAiOjE3NTU3NTY2NDUsImlhdCI6MTc1NTc1NjU4NSwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo1MTMxIiwiYXVkIjoiaHR0cDovL2xvY2FsaG9zdDo1MTMxIn0.b-ov4fpyC6lymwxl4ReOF_B3ZxyR8vT0et0DU9rAcgU",
  "refreshToken": "cXJcDn1sl/C+IBSGl14H+rWvbzRd9KhCyc4mIEvvxh0="
}

###
GET {{base_address}}/me
Authorization: Bearer {{accessToken}}

###
POST {{base_address}}/refresh
Authorization: Bearer {{accessToken}}

###
POST {{base_address}}/logout
Authorization: Bearer {{accessToken}}